services:
  # Backend Server
  - type: web
    name: mandanten-portal-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ZENDESK_SUBDOMAIN
        sync: false
      - key: ZENDESK_EMAIL
        sync: false
      - key: ZENDESK_API_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Frontend
  - type: web
    name: mandanten-portal-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html